[package]
name = "feq"
version = "0.1.0"
authors = ["Ioannis Giagkiozis"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
